# Generated by Django 2.2.4 on 2019-09-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190902_1841'),
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('P', 'Physical Aptitude'), ('A', 'Artistic Skill'), ('B', 'Biological Science'), ('H', 'Human Science'), ('E', 'Exact Science'), ('S', 'Social Skill')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Ameba'), (2, 'Vegetal'), (3, 'Ser Pensante'), (4, 'Malandrão'), (5, 'Topzera')], default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='tinder.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
