# Generated by Django 2.2.4 on 2019-10-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_auto_20190925_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=False, help_text='Is this group hidden from others?'),
        ),
    ]
