# Generated by Django 2.2.5 on 2019-10-28 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0004_group_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='foundation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='tinder.Skill'),
        ),
    ]
