# Generated by Django 2.2.6 on 2019-12-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0005_auto_20191028_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='passwd',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
