# Generated by Django 2.2.7 on 2019-12-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0007_auto_20191210_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
