# Generated by Django 2.2.4 on 2019-09-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_skill_skilllevel'),
        ('accounts', '0002_auto_20190902_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='profiles', through='tinder.SkillLevel', to='tinder.Skill'),
        ),
    ]
