# Generated by Django 2.2.5 on 2019-10-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shortbio',
            field=models.TextField(default="This user's shortbio hasn't been defined yet.", help_text='A short description of the person'),
        ),
    ]
