# Generated by Django 2.2.4 on 2019-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_skill_skilllevel'),
        ('accounts', '0003_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(related_name='members', to='tinder.Group'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shortbio',
            field=models.TextField(default="This user's shortbio hasn't been defined yet.", help_text='A short description of the person'),
        ),
    ]
