# Generated by Django 2.2.7 on 2019-12-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shortbio',
            field=models.TextField(blank=True, help_text='A short description of the person'),
        ),
    ]
