# Generated by Django 2.2.7 on 2019-12-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shortbio',
            field=models.TextField(blank=True),
        ),
    ]
